name: GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkmeout
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setupnode
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install
        id: runinstall
        run: npm install

      - name: Build
        id: runbuild
        run: ng build --base-href /antiscam-bl/ --output-path gh-pages

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: gh-pages/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GH Pages
      if: success()
      uses: actions/deploy-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/antiscam-blocklist
        enable_jekyll: true
